name: cd20_binder_design
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy=1.23.5
  - pandas
  - matplotlib
  - jupyter
  - ipykernel
  - mdanalysis
  - pymol-open-source
  - biopython
  - openmm
  - pip:
    - torch==1.9.0
    - torchvision==0.10.0
    - "git+https://github.com/RosettaCommons/pyrosetta.git"